# General settings
requireMinimumPlayers: true  # Set to false to disable the requirement of 5 players online to start a competition
timezone: "CET"  # Set the timezone for competition scheduling (e.g., "UTC", "CET", "America/New_York")

competitionPeriods:
  - "00.00 - 00.05"
  - "01.00 - 01.05"
  - "02.00 - 02.05"
  - "03.00 - 03.05"
  - "04.00 - 04.05"
  - "05.00 - 05.05"
  - "06.00 - 06.05"
  - "07.00 - 07.05"
  - "08.00 - 08.05"
  - "09.00 - 09.05"
  - "10.00 - 10.05"
  - "11.00 - 11.05"
  - "12.00 - 12.05"
  - "13.00 - 13.05"
  - "14.00 - 14.05"
  - "15.00 - 15.05"
  - "16.00 - 16.05"
  - "17.00 - 17.05"
  - "18.00 - 18.05"
  - "19.00 - 19.05"
  - "20.00 - 20.05"
  - "21.00 - 21.05"
  - "22.00 - 22.05"
  - "23.00 - 23.05"

Wheat:
  "1":
    command: "eco give %NAME% 100000"
    message: "&c&lREWARD! &7You received: &c100000&7!"
  "2":
    command: "crate give to %player% rare 5"
    message: "&c&lREWARD! &7You received: &c5 Rare Keys&7!"
  "3":
    command: "crate give to %player% spawner 5"
    message: "&c&lREWARD! &7You received: &c5 Spawner Keys&7!"
  "4":
    command: "crate give to %player% legendary 5"
    message: "&c&lREWARD! &7You received: &c5 Legendary Keys&7!"
  "5":
    command: "crate give to %player% premium 5"
    message: "&c&lREWARD! &7You received: &c5 Premium Keys&7!"
  "6":
    command: "wildstacker:stacker give %player% spawner cow 10"
    message: "&c&lREWARD! &7You received: &c10 Cow Spawners&7!"
  "7":
    command: "wildstacker:stacker give %player% spawner llama 10"
    message: "&c&lREWARD! &7You received: &c10 Llama Spawners&7!"
  "8":
    command: "wildstacker:stacker give %player% spawner polar_bear 10"
    message: "&c&lREWARD! &7You received: &c10 Polar Bear Spawners&7!"

Nether_Wart:
  "1":
    command: "eco give %NAME% 100000"
    message: "&c&lREWARD! &7You received: &c100000&7!"
  "2":
    command: "crate give to %player% rare 5"
    message: "&c&lREWARD! &7You received: &c5 Rare Keys&7!"
  "3":
    command: "crate give to %player% spawner 5"
    message: "&c&lREWARD! &7You received: &c5 Spawner Keys&7!"
  "4":
    command: "crate give to %player% legendary 5"
    message: "&c&lREWARD! &7You received: &c5 Legendary Keys&7!"
  "5":
    command: "crate give to %player% premium 5"
    message: "&c&lREWARD! &7You received: &c5 Premium Keys&7!"
  "6":
    command: "wildstacker:stacker give %player% spawner cow 10"
    message: "&c&lREWARD! &7You received: &c10 Cow Spawners&7!"
  "7":
    command: "wildstacker:stacker give %player% spawner llama 10"
    message: "&c&lREWARD! &7You received: &c10 Llama Spawners&7!"
  "8":
    command: "wildstacker:stacker give %player% spawner polar_bear 10"
    message: "&c&lREWARD! &7You received: &c10 Polar Bear Spawners&7!"

Potato:
  "1":
    command: "eco give %NAME% 100000"
    message: "&c&lREWARD! &7You received: &c100000&7!"
  "2":
    command: "crate give to %player% rare 5"
    message: "&c&lREWARD! &7You received: &c5 Rare Keys&7!"
  "3":
    command: "crate give to %player% spawner 5"
    message: "&c&lREWARD! &7You received: &c5 Spawner Keys&7!"
  "4":
    command: "crate give to %player% legendary 5"
    message: "&c&lREWARD! &7You received: &c5 Legendary Keys&7!"
  "5":
    command: "crate give to %player% premium 5"
    message: "&c&lREWARD! &7You received: &c5 Premium Keys&7!"
  "6":
    command: "wildstacker:stacker give %player% spawner cow 10"
    message: "&c&lREWARD! &7You received: &c10 Cow Spawners&7!"
  "7":
    command: "wildstacker:stacker give %player% spawner llama 10"
    message: "&c&lREWARD! &7You received: &c10 Llama Spawners&7!"
  "8":
    command: "wildstacker:stacker give %player% spawner polar_bear 10"
    message: "&c&lREWARD! &7You received: &c10 Polar Bear Spawners&7!"

Carrot:
  "1":
    command: "eco give %NAME% 100000"
    message: "&c&lREWARD! &7You received: &c100000&7!"
  "2":
    command: "crate give to %player% rare 5"
    message: "&c&lREWARD! &7You received: &c5 Rare Keys&7!"
  "3":
    command: "crate give to %player% spawner 5"
    message: "&c&lREWARD! &7You received: &c5 Spawner Keys&7!"
  "4":
    command: "crate give to %player% legendary 5"
    message: "&c&lREWARD! &7You received: &c5 Legendary Keys&7!"
  "5":
    command: "crate give to %player% premium 5"
    message: "&c&lREWARD! &7You received: &c5 Premium Keys&7!"
  "6":
    command: "wildstacker:stacker give %player% spawner cow 10"
    message: "&c&lREWARD! &7You received: &c10 Cow Spawners&7!"
  "7":
    command: "wildstacker:stacker give %player% spawner llama 10"
    message: "&c&lREWARD! &7You received: &c10 Llama Spawners&7!"
  "8":
    command: "wildstacker:stacker give %player% spawner polar_bear 10"
    message: "&c&lREWARD! &7You received: &c10 Polar Bear Spawners&7!"
